import client from "@/client";
import {Post} from "@/types";
import {Metadata} from "next";

type PageProps = {
    params: {
        slug: string;
    }
};

export async function generateMetadata({params}: PageProps): Promise<Metadata> {
    const post = await client.fetch<Post | null>(`*[_type == 'post' && slug.current == $slug][0] {
      "key": _id,
      title,
      "slug": slug.current,
      publishedAt
    }`, {
        slug: params.slug
    })

    if (!post) {
        return {};
    }

    return {
        title: `${post.title} | CoolRecipes`,
        // description: 'Generated by create next app',
        openGraph: {
            title: post.title,
            // description: 'The React Framework for the Web',
            url: ``,
            siteName: 'CoolRecipes',
            images: [
                {
                    url: 'https://nextjs.org/og.png',
                    width: 800,
                    height: 600,
                },
            ],
            locale: 'en_US',
            type: 'website',
        },
    };
}


export default function Home({params}: PageProps) {
    // return <PostCard slug={params.slug}/>
    return <div>{params.slug}</div>;
}

export async function generateStaticParams() {
    return await client.fetch<string[]>(`
        *[_type == 'post'] {
          "slug": slug.current
        }
    `);
}
