import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    metadataBase: new URL(`${process.env.NEXT_PUBLIC_FRONTEND_SCHEMA}://${process.env.NEXT_PUBLIC_FRONTEND_HOST}`),
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" data-foo={"bar"}>
        <body className={inter.className}>{children}</body>
        </html>
    )
}
